import { i18n } from '@/shared/locale'

const DRINK_TYPE = {
  mix: 'mix',
  original: 'original',
}

const DRINK_MENU = [
  {
    id: '1',
    name: i18n.t('menu.drinks.orange'),
    value: 'orange',
    price: 20000,
    description: i18n.t('menu.drinks.descriptions.orange'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '2',
    name: i18n.t('menu.drinks.apple'),
    value: 'apple',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.apple'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '3',
    name: i18n.t('menu.drinks.pineapple'),
    value: 'pineapple',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.pineapple'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '4',
    name: i18n.t('menu.drinks.watermelon'),
    value: 'watermelon',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.watermelon'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '5',
    name: i18n.t('menu.drinks.celery'),
    value: 'celery',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.celery'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '8',
    name: i18n.t('menu.drinks.guava'),
    value: 'guava',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.guava'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.original,
  },
  {
    id: '6',
    name: `${i18n.t('menu.drinks.apple')} + ${i18n.t('menu.drinks.orange')}`,
    value: 'apple,orange',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.appleorange'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.mix,
  },
  {
    id: '7',
    name: `${i18n.t('menu.drinks.apple')} + ${i18n.t('menu.drinks.guava')}`,
    value: 'apple,guava',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.appleguava'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.mix,
  },
  {
    id: '9',
    name: `${i18n.t('menu.drinks.apple')} + ${i18n.t('menu.drinks.pineapple')}`,
    value: 'apple,pineapple',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.applepineapple'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.mix,
  },
  {
    id: '10',
    name: `${i18n.t('menu.drinks.apple')} + ${i18n.t('menu.drinks.celery')}`,
    value: 'apple,celery',
    price: 25000,
    description: i18n.t('menu.drinks.descriptions.applecelery'),
    image: '/api/placeholder/300/200',
    type: DRINK_TYPE.mix,
  },
]

export { DRINK_MENU, DRINK_TYPE }
